### ISSUE TITLE
Error after successfull login. 

### ISSUE THREAD

**Issue by MichaelErmer** [tinyclues/saltpad#57]
Running the newest salt-master and and api from the ppa.
salt-api 2015.5.0
salt-master 2015.5.0 (Lithium)

Python 2.7.6
Werkzeug (0.10.4)

```
Traceback (most recent call last):
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/saltpad/saltpad/app.py", line 57, in wrapper
    return view(*args, **kwargs)
  File "/opt/saltpad/saltpad/app.py", line 105, in index
    jobs = sorted(client.jobs().items(), reverse=True)[:10]
AttributeError: 'unicode' object has no attribute 'items'
````
If i change line 105:
```
    jobs=[]
    if (isInstance(client.jobs(), dict)):
      jobs = sorted(client.jobs().items(), reverse=True)[:10]
```
 I can at least load the frontpage, thers similar errors on other pages. 

As there are no other issues, im wondering if that is that some kind of python/werkzeug version problem?

**Comment by alexandr-orlov** [comment]
I have a similar problem with:
salt-api  2014.7.4
salt-master  2014.7.4
Python 2.7.3

**Comment by Lothiraldan** [comment]
The problem is likely to be on the salt-api. The output format of salt-api depends on the master_job_cache used for storing (and retrieving) jobs. That makes the saltpad job much more difficult.

Which master_job_cache do you use? Either default or a custom one?

**Comment by alexandr-orlov** [comment]
I'm using  default ('local_cache') master_job_cache.

**Comment by whiteinge** [comment]
If the output format from Salt differs if you're using ext_job_cache
vs master_job_cache vs returner that is a bug; please file an issue on
the Salt repository with the details (and please tag me on it as
well).

**Comment by Lothiraldan** [comment]
@KrustyHack I've worked on compatibility with 2015.5.X version, could you please try https://github.com/tinyclues/saltpad/pull/71 and comment if you prefer compatibility with 2015.5.X version or 2014.7.X version?

**Comment by KrustyHack** [comment]
Hi,

Thanks a lot. I Will try that asap. :)

Regards,

**Comment by andrewpsuedonym** [comment]
I'm getting this too, it only started happening for me after I pulled from the repo this morning.

**Comment by Lothiraldan** [comment]
@andrewpsuedonym Which salt version do you use and which salt-api provider do you use?

**Comment by andrewpsuedonym** [comment]
# salt --versions-report
           Salt: 2015.5.2
         Python: 2.7.10 (default, May 30 2015, 02:17:57)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.3
         PyYAML: 3.11
          ioflo: 1.2.1
          PyZMQ: 14.6.0
           RAET: 0.6.3
            ZMQ: 4.1.2
           Mako: 1.0.1

# salt-api --version
  salt-api 2015.5.2

**Comment by phryneas** [comment]
Same problem here:

                  Salt: 2015.5.2
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.2+ds-1trusty1

and 

    # salt-api --version
    salt-api 2015.5.2

**Comment by Lothiraldan** [comment]
@andrewpsuedonym @phryneas Do you have minions in 2014.7.X version?

**Comment by andrewpsuedonym** [comment]
@Lothiraldan No, all of mine are 2015.5.3

**Comment by phryneas** [comment]
on all systems:
```
ii  salt-common                         2015.5.2+ds-1trusty1             all          shared libraries that salt requires for all packages
ii  salt-minion                         2015.5.2+ds-1trusty1             all          client package for salt, the distributed remote execution
```

**Comment by phryneas** [comment]
Oh, and for provider and access rights:

rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key

external_auth:
  pam:
    phry:
        - .*
        - '@runner'
        - '@wheel'

**Comment by KrustyHack** [comment]
Working fine for me.

**Comment by charles-d-burton** [comment]
I'm having this issue as well.

salt --versions-report
           Salt: 2015.5.2
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

**Comment by hemebond** [comment]
I believe this is caused by https://github.com/saltstack/salt/issues/22734

**Comment by scubahub** [comment]
Im having the same issue one one (of 2) salt masters:

```
> salt --versions-report
           Salt: 2015.5.9
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.8
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: Not Installed
```

```
Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/saltpad/saltpad/app.py", line 63, in wrapper
    return view(*args, **kwargs)
  File "/var/www/saltpad/saltpad/app.py", line 112, in index
    jobs = sorted(list(client.jobs().items()), reverse=True)[:10]
AttributeError: 'unicode' object has no attribute 'items'
```

**Comment by Lothiraldan** [comment]
I've since rewrite Saltpad in React.js to ease deployment and have a more interactive interface, could you please give it a try and see if it works for you?
